### ISSUE TITLE
dcron.Start() 卡住

### ISSUE THREAD

**Issue by wang198927** [libi/dcron#110]
dcron.Start() 卡住

**Comment by dxyinme** [comment]
使用的是什么版本的dcron，能给一段代码帮助复现一下问题吗

**Comment by wang198927** [comment]
> 使用的是什么版本的dcron，能给一段代码帮助复现一下问题吗

版本是最新的 0.6.0 

func NewWorker(redisCli redis.UniversalClient, repo repo) *Worker {
	return &Worker{d: dcron.NewDcron("service", redisdriver.NewDriver(redisCli)), repo: repo}
}

func (w *Worker) Start() {
	if err = w.d.AddFunc("test1", "*/3 * * * *", func() {
		log.Infof("execute test1 task: %s", time.Now().Format("15:04:05"))
	}); err != nil {
		log.Errorf("AddFunc err")
	}
	w.d.Start() // 卡住，后续没有打印
}

**Comment by dxyinme** [comment]
```go
package main

import (
	"time"

	"log"

	"github.com/alicebob/miniredis/v2"
	"github.com/dcron-contrib/redisdriver"
	"github.com/libi/dcron"
	"github.com/redis/go-redis/v9"
)

type worker struct {
	d *dcron.Dcron
}

func NewWorker(redisCli redis.UniversalClient) *worker {
	return &worker{d: dcron.NewDcron("service", redisdriver.NewDriver(redisCli))}
}

func (w *worker) Start() {
	if err := w.d.AddFunc("test1", "*/3 * * * *", func() {
		log.Printf("execute test1 task: %s", time.Now().Format("15:04:05"))
	}); err != nil {
		log.Println("AddFunc err")
	}
	w.d.Start()

	log.Println("Start finished")
}

func main() {
	localkv := miniredis.NewMiniRedis()
	localkv.Start()
	redisClient := redis.NewClient(&redis.Options{
		Addr: localkv.Addr(),
	})
	w := NewWorker(redisClient)
	w.Start()
	<-time.After(10 * time.Minute)
}

```

**Comment by dxyinme** [comment]
@wang198927 您好，我这里写了一个最小可用的demo，发现并没有出现卡死的问题，仔细想想可能是因为您的cron表达式是分钟级别的，需要等比较长时间，建议检查本地redis链接是否可用，或者可以使用秒级的cron。
