### ISSUE TITLE
负载均衡怎么配置

### ISSUE THREAD

**Issue by piupuer** [libi/dcron#17]
你好，启动了多个实例在不同种类的机器上运行
![image](https://user-images.githubusercontent.com/27284001/144181141-87c8663e-17ae-45e9-9c60-226f4b18dcaf.png)
![image](https://user-images.githubusercontent.com/27284001/144181167-ebd8c52b-ea34-4032-9a9b-1fd07532a970.png)
![image](https://user-images.githubusercontent.com/27284001/144182107-5821a8c4-64b3-4ae5-aa57-d8c804f13aa9.png)
![image](https://user-images.githubusercontent.com/27284001/144182126-611b7845-9683-46c9-ad12-5b865082f960.png)
当停掉某个节点，会自动切换，这是没问题的，但是如果各个节点都稳定运行时，怎么做到负载均衡？

**Comment by libi** [comment]
dcron使用的一致性哈希算法进行任务节点分配，这是为了保障在有节点故障时最少的节点迁移，同时实现部分负载均衡。所以dcron暂时不支持自定义的负载均衡。
如果某个任务单节点性能无法支撑的话，建议拆分任务为更细粒度的n个子任务，由dcron自由分配来模拟负载均衡。

**Comment by piupuer** [comment]
感谢来信，但您所发的用户不在服务区，请稍后再发！
