### ISSUE TITLE
dcron时间表达式，跟传统的表达式不一样，貌似不支持秒级别。希望能出个详细的使用例子和表达式该怎么写

### ISSUE THREAD

**Issue by lzr1994** [libi/dcron#18]

**Comment by libi** [comment]
readme 已经补充了秒级表达式的用法

**Comment by wjlzr** [comment]
@libi 我加了秒级的用法 结果方法里一直在内部循环 一秒一次 循环一分钟后结束 等待外面设置的任务表达式的时间到了后 进入到这个方法又开始一秒一次的内部循环

**Comment by lzr1994** [comment]
我已经弃用了，这个bug还挺多的，不敢用了，还得自己写一个简单的就行了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "libi/dcron"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月8日(星期一) 中午11:43
***@***.***&gt;;
抄送:&nbsp;"Rose ***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [libi/dcron] dcron时间表达式，跟传统的表达式不一样，貌似不支持秒级别。希望能出个详细的使用例子和表达式该怎么写 (Issue #18)





 
@libi 我加了秒级的用法 结果方法里一直在内部循环 一秒一次 循环一分钟后结束 等待外面设置的任务表达式的时间到了后 进入到这个方法又开始一秒一次的内部循环

**Comment by libi** [comment]
> 一秒一次



> @libi 我加了秒级的用法 结果方法里一直在内部循环 一秒一次 循环一分钟后结束 等待外面设置的任务表达式的时间到了后 进入到这个方法又开始一秒一次的内部循环

描述我没太理解，可以贴一下示例代码吗

**Comment by libi** [comment]
@lzr1994 可以说一下遇到的具体 bug 是什么哈，我排查一下。
