### ISSUE TITLE
etcd driver's `ping` function not implement.

### ISSUE THREAD

**Issue by dxyinme** [libi/dcron#31]
https://github.com/libi/dcron/blob/master/driver/etcd/etcd_driver.go#L147
是否需要用etcd.Status这个接口来实现ping？

**Comment by dxyinme** [comment]
https://github.com/libi/dcron/blob/master/driver/redis/redis_driver.go#L82  
ping的实现方式是否可以直接用redis的ping代替
可以的话我最近搞个pr修一下类似的东西，并且增加一下英文doc

**Comment by libi** [comment]
etcd的watch内部有类似ping的实现 所以可以不用ping方法
