### ISSUE TITLE
可以支持固定间隔的定时任务吗

### ISSUE THREAD

**Issue by wind-hx** [libi/dcron#65]
比如间隔5秒执行一次，当任务启动的时候服务器时间是
00:02 下一次执行应该是 00:07，而并非Cron的00:05

**Comment by libi** [comment]
这个暂时不支持哦，因为涉及到分布式的话各个节点间启动时间可能存在差异，
比如节点A在00.00启动他的下一次任务是在00.05，节点B在00.02启动他的下一次任务是在00.07。 所以实现会比较复杂。

不过当前设计下可以使用这种方案，比如定时任务用 1 秒，然后在业务层判断 currtime%5-2 == 0 执行业务逻辑就可以了。

**Comment by little0919** [comment]
我看现在是支持了的是吗？  
一个任务不是只能在固定一个节点上运行吗，那貌似不存在 "节点A在00.00启动他的下一次任务是在00.05，节点B在00.02启动他的下一次任务是在00.07" 这种问题？
