### ISSUE TITLE
增加codecov看板

### ISSUE THREAD

**Issue by dxyinme** [libi/dcron#82]
https://docs.codecov.com/docs/quick-start
@libi 
我觉得可以按照这个教程配置一下codecov的看板（由于需要owner权限所以我做不了这个事情），这样子用户对库也会更有信心。

**Comment by libi** [comment]
好的 我看着加下

**Comment by libi** [comment]
> https://docs.codecov.com/docs/quick-start @libi 我觉得可以按照这个教程配置一下codecov的看板（由于需要owner权限所以我做不了这个事情），这样子用户对库也会更有信心。

已经加上啦， 你登录一次 codecov 应该就自动加入成员组了

**Comment by dxyinme** [comment]
好的感谢
