### ISSUE TITLE
不支持redis集群？

### ISSUE THREAD

**Issue by yueqianlong** [libi/dcron#90]
driver不支持redis集群？

**Comment by dxyinme** [comment]
曾经有过一个redisClusterDriver,但是由于很难进行良好的测试所以删除了，如果需要的话可以自己实现[DriverV2](https://github.com/libi/dcron/blob/master/driver/driver.go)接口，或者也可以提出建议或者提交PR实现redisClusterDriver

**Comment by dxyinme** [comment]
最新的v0.5.5版本支持了
