### ISSUE TITLE
stop优化

### ISSUE THREAD

**Issue by jiangfuquan-ola** [libi/dcron#99]
cron的stop是有返回一个context，可以判断，context.Done正在执行的任务是否都完成了
Dcron的stop忽略了这个参数，应该优化一下，支持等待任务完成

**Comment by dxyinme** [comment]
可以的，这个我看一看

**Comment by dxyinme** [comment]
https://github.com/libi/dcron/pull/100

**Comment by dxyinme** [comment]
这个PR已经合入develop分支，会在一段时间后的release中发布
